"""Partial zip reads keep already-collected evidence (#164).

One unreadable member used to discard every C2PA/AI marker found in earlier
members and replace them with a hardcoded clean-looking result. Evidence must
survive, with a note naming the partial read.
"""

from __future__ import annotations

import io
import sys
import zipfile
import zlib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SCRIPTS = ROOT / "service" / "scripts"
sys.path.insert(0, str(SCRIPTS))

import container_meta

MARKER = b"<dc:creator>c2pa contentcredentials OpenAI</dc:creator>"


def _docx_bytes() -> bytes:
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("[Content_Types].xml", "<?xml version='1.0'?><Types/>")
        zf.writestr("word/document.xml", "<w:document/>")
        zf.writestr("docProps/core.xml", MARKER)
        zf.writestr("customXml/item1.xml", "<root/>")
    return buf.getvalue()


def _fail_read_for(container_meta, fail_member: str):
    """Make _read_zip_member raise zlib.error for fail_member (deterministic
    member-read failure with an intact archive structure — the real-world
    triggers per the issue: corrupt deflate, CRC mismatch, unsupported
    compression, encrypted member)."""
    orig = container_meta._read_zip_member

    def flaky(zf, info, budget):
        if info.filename == fail_member:
            raise zlib.error("Error -3 while decompressing data: invalid code lengths set")
        return orig(zf, info, budget)

    container_meta._read_zip_member = flaky
    return lambda: setattr(container_meta, "_read_zip_member", orig)


def test_corrupt_later_member_keeps_earlier_evidence():
    # docProps/core.xml is read before customXml/*; failing the later member
    # must not discard the earlier marker evidence.
    restore = _fail_read_for(container_meta, "customXml/item1.xml")
    try:
        has_c2pa, has_ai, findings, _meta = container_meta.inspect_docx(_docx_bytes())
    finally:
        restore()
    assert has_c2pa and has_ai, findings
    assert any("docProps/core.xml" in f for f in findings), findings
    assert any("partial read" in f.lower() for f in findings), findings


def test_odt_partial_read_keeps_evidence():
    # mimetype sorts first; failing content.xml (read after it) keeps the
    # mimetype blob evidence and the meta.xml generator finding.
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w") as zf:
        zf.writestr("mimetype", "application/vnd.oasis.opendocument.text c2pa")
        zf.writestr("content.xml", "<office:document-content/>")
        zf.writestr("meta.xml", "<meta:generator>Claude</meta:generator>")
    restore = _fail_read_for(container_meta, "content.xml")
    try:
        has_c2pa, _has_ai, findings, _ = container_meta.inspect_odt(buf.getvalue())
    finally:
        restore()
    assert has_c2pa, findings
    assert any("mimetype" in f for f in findings), findings
    assert any("partial read" in f.lower() for f in findings), findings


def test_epub_partial_read_keeps_evidence():
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w") as zf:
        zf.writestr("mimetype", "application/epub+zip")
        zf.writestr("META-INF/container.xml", "<container/>")
        zf.writestr("content.opf", "<dc:creator>Generated by OpenAI</dc:creator>")
        zf.writestr("chapter1.xhtml", "<html>ok</html>")
    restore = _fail_read_for(container_meta, "chapter1.xhtml")
    try:
        has_ai, findings = None, None
        r = container_meta.inspect_epub(buf.getvalue())
        _has_c2pa, has_ai, findings, _ = r
    finally:
        restore()
    assert has_ai, findings
    assert any("content.opf" in f for f in findings), findings
    assert any("partial read" in f.lower() for f in findings), findings


def test_wholly_garbage_bytes_keep_not_a_valid_shape():
    has_c2pa, has_ai, findings, _ = container_meta.inspect_docx(b"not a zip at all")
    assert has_c2pa is False and has_ai is False
    assert findings == ["not a valid DOCX zip"]


def test_intact_docx_finds_markers_without_partial_note():
    has_c2pa, _has_ai, findings, _ = container_meta.inspect_docx(_docx_bytes())
    assert has_c2pa is True
    assert any("docProps/core.xml" in f for f in findings)
    assert not any("partial read" in f.lower() for f in findings)
